#pragma once
#include <iostream>
#include <Windows.h>
#include <vector>
using namespace std;


void Swim(int State, const char *User);
void Particle(int State, const char *User);
void GuestChat(int State);
void NoclipRL(int State, const char *user);
void NoclipLA(int State, const char *user);
void NoclipRA(int State, const char *user);
void NoclipLL(int State, const char *user);
void NoRarm(int State, const char *user);
void NoLleg(int State, const char *user);
void NoRleg(int State, const char *user);
void NoLarm(int State, const char *user);
void NoTorso(int State, const char *user);
void Invisible(int State, const char *user);
void RemoveMessage(int State);
void Message(int State, const char *message);
void Walkspeed(int State, const char *user, int Speed);
void Forcefield(int State, const char *user);
void Sparkles(int State, const char *user);
void Fire(int State);
void UnSparkles(int State);
void Kill(int State, const char *user);
void Loopkill(int State, const char *user);
void Kick(int State, const char *user);
void UnFF(int State, const char *user);
void Fire(int State, const char *user);
void Bonfire(int State, const char *user);
void Smoke(int State, const char *user);
void God(int State, const char *user);
void TimeSet(int State, double time);
void NoHead(int State, const char *user);
void JumpPower(int State, const char *user, int JumpPower);
void Fling(int State, const char *user);
void Music(int State, const char *id, std::string str);
void TP(int State, const char *user1, const char *user2);
void Freeze(int State, const char *user);
void Thaw(int State, const char *user);
void Sit(int State, const char *user);
void SetMaxHealth(int State, const char *user, int Health);
void SetHealth(int State, const char *user, int Health);
void Demigod(int State, const char *user);
bool getFiltering(int State);
void GlobalShadows(int State, int TrueOrFalse);
void Fog(int State);
void DestroyFog(int State);
void SetBrightness(int State, double brightness);
void ClearTerrain(int State);
void Btools(int State, const char *user);
void Stat(int State, const char *user, const char *stat, int value);
void StatCreate(int State, const char *user);
void RenameStat(int State, const char *user, const char *stat, const char *name);
void Char(int State, const char *user, int id);
void HttpEnable(int State);
void PrivateMessage(int State, const char *user, const char *message);
int StopMusic(int State);
void RemoveTools(int State, const char *user, const char *tool);
void Print(int State, const char *msg);
void GlobalShadows(int State);
void DisableTurns(int State, const char *user);
void EnableShadows(int State);
void EnableTurns(int State, const char *user);
void Ragdoll(int State, const char *user);
void DisableAnimations(int State, const char *user);
void EnableAnimations(int State, const char *user);
void Noob(int State, const char *user);
void Regular(int State, const char *user);
void QuickSand1(int State, const char *user);
void RagdollEnd(int State, const char *user);
void Warn(int State, const char *msg);
void AmbientV2(int State);
void RemoveFF(int State, const char *user);
void RemoveSparkles(int State, const char *user);
void RemoveFire(int State, const char *user);
void Check(int State);
void CrashPlayer(int State, const char *user);
void Skybox(int State);
void RemoveRagdoll1(int State, const char *user);
void Ragdoll1(int State, const char *user);
void Mesh(int State, const char *User);